### ISSUE TITLE
Clean up math encoding

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/S-102-Product-Specification#1]
<img width="732" alt="Screen Shot 2022-11-03 at 8 11 09 PM" src="https://user-images.githubusercontent.com/11865/199717143-21049012-4fa8-4528-98c7-51701d8f2a73.png">

**Comment by ronaldtse** [comment]
The math encoding isn't accurate. Right now:

```adoc
==== Sonar footprint
Sonar footprint is a function of water depth (20 metres) and beam angle (0.5° X 0.5°). Computed footprint at nadir:

Footprint @ Nadir = stem:[2 x (("Depth") x (Tan Ø/2))], where Ø = Beam Width stem:["Footprint" = 2 x ((20 m) x (Tan .25)) = 0.17 "metres"]

Since this is a stem:[0.5° x 0.5°] system, the total footprint at Nadir is: stem:[0.17m x 0.17m]
```

e.g.
* `stem:[2 x (("Depth") x (Tan Ø/2))]` should probably be `stem:[2 xx ("Depth" xx tan(Ø/2))]`
* `stem:[0.17m x 0.17m]` should be `stem:[0.17"m" xx 0.17"m"]`

**Comment by anermina** [comment]
Changes are merged. Closing.
